service: puppeteerwithlambda

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 512
  timeout: 60
  region: ap-northeast-2
functions:
  start:
    handler: src/index.handler
    events:
      - http:
          path: /start
          method: get
